### ISSUE TITLE
Customisation for matching wikidata to cities

### ISSUE THREAD

**Issue by bsrinivasa** [mapbox/wikimama#10]
The current Wikimama script looks for neighbourhoods around a city for a specified radius and thresholds.

Customisation for matching cities
- Compare list of cities from OSM with list of features which are instances of cities in Wikidata
- Option to vary threshold

Basically, Wikimama tool for cities would be comparing names from both the platform and scores accordingly and derives the difference in distance b/w the co-ordinates from both the platforms. 

The threshold would be tweaked based on the initial output from Wikimama.

cc: @amishas157 @planemad @abhisheksaikia @chtnha @kupendrayadav @geohacker

**Comment by amishas157** [comment]
[Here](https://github.com/mapbox/wikimama/tree/city-matching) is the customized script for city matching:

To run: `node batch-match.js --file input.csv` , where `input.csv` contains the threshold value

cc @bsrinivasa

**Comment by geohacker** [comment]
@amishas157 rather than having this code in a branch, can you make this an option we can pass to the main script to take what type of feature we want to match?

**Comment by planemad** [comment]
👍 @geohacker

We should just take the search radius as an option `--radius` while running the script. 

The input could then be either:
- input.csv of a list of locations with lat/lons and an Overpass query.ql to generate OSM features
- input.geojson of OSM features generated from Overpass

**Comment by bsrinivasa** [comment]
@geohacker @amishas157 We might not have a chance to do this again. In this iteration, we would be matching corresponding wikidata entities for almost of the cities in OSM. The only case where we might use this again is when there are new cities added to OSM which do not have wikidata items tagged to it. Should we still make it generic for various types of input? 

cc: @planemad

**Comment by geohacker** [comment]
I think we should, if it's not a huge lift.

**Comment by bsrinivasa** [comment]
The tool was optimised for matching cities. Check out the **[branch](https://github.com/mapbox/wikimama/tree/city-matching)** 🎉 . Thank you @amishas157  for quickly building this. 🙂 

Tracking further discussion on generic inputs at #13. Closing this ticket. 🚀
