### ISSUE TITLE
New fields for output.csv

### ISSUE THREAD

**Issue by bsrinivasa** [mapbox/wikimama#8]
Add `osm_type`, `wikidata_qid` and  `JOSM url` fields in `output.csv` which would help anyone working on it to quickly add the exact match using JOSM editor. Here is an [example](https://github.com/bsrinivasa/wikimama/blob/Improvements/js/augment_wikidata_csv.js#L188) for JOSM URL for adding Wikidata tags. 

The `place` field should ideally have the the category of OSM feature that it belongs to. Ex: neighbourhood, suburb, tourism, city, town, etc. but currently link to wikidata url has been generated under this field. 

_Priority: Medium_ 

cc: @amishas157

**Comment by amishas157** [comment]
@bsrinivasa ,

Fixed here: https://github.com/mapbox/wikimama/commit/fbffbbdaf7791b0c7e7cdd74c07c978367f2ff91
